#!/usr/bin/env bash

mkdir -p /usr/local/share/ca-certificates/extra
cd /usr/local/share/ca-certificates/extra

# Remove expired root certificates to work around OpenSSL 1.0.x issue.
sed -i 's/^\(mozilla\/AddTrust_External_Root.crt\)$/!\1/' /etc/ca-certificates.conf

update-ca-certificates

# Manually get intermediate CA certificates to deal with websites that don't
# serve a full certificate chain. These are misconfigured websites, but we want
# to be able to handle them anyways.
wget https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt -O lets-encrypt-x3-cross-signed.crt
wget https://spaces.at.internet2.edu/download/attachments/24576265/InCommonRSAServerCA_2.crt

update-ca-certificates
